apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: secure-web
  template:
    metadata:
      labels:
        app: secure-web
    spec:
      containers:
      - name: web-container
        image: nginx:1.25
        ports:
        - containerPort: 80


apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc  # 服务名称
spec:
  type: NodePort  # 节点端口类型
  selector:
    app: secure-web  # 必须与Deployment中Pod标签匹配
  ports:
  - name: http
    protocol: TCP
    port: 80          # Service的端口（CLB通过此端口访问）
    targetPort: 80     # 容器监听的端口（Pod端口）
    nodePort: 31000    # 节点端口（30000-32767范围）



apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nodeport-svc  # 关联您创建的NodePort Service
            port:
              number: 80        # Service端口



